/*
Copyright (c) 2025 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module bindbc.physfs.funcs;

import bindbc.physfs.prototypes;

__gshared
{
    da_PHYSFS_getLinkedVersion PHYSFS_getLinkedVersion;
    da_PHYSFS_init PHYSFS_init;
    da_PHYSFS_deinit PHYSFS_deinit;
    da_PHYSFS_supportedArchiveTypes PHYSFS_supportedArchiveTypes;
    da_PHYSFS_freeList PHYSFS_freeList;
    da_PHYSFS_getLastError PHYSFS_getLastError;
    da_PHYSFS_getDirSeparator PHYSFS_getDirSeparator;
    da_PHYSFS_permitSymbolicLinks PHYSFS_permitSymbolicLinks;
    da_PHYSFS_getCdRomDirs PHYSFS_getCdRomDirs;
    da_PHYSFS_getBaseDir PHYSFS_getBaseDir;
    da_PHYSFS_getUserDir PHYSFS_getUserDir;
    da_PHYSFS_getWriteDir PHYSFS_getWriteDir;
    da_PHYSFS_setWriteDir PHYSFS_setWriteDir;
    da_PHYSFS_addToSearchPath PHYSFS_addToSearchPath;
    da_PHYSFS_removeFromSearchPath PHYSFS_removeFromSearchPath;
    da_PHYSFS_getSearchPath PHYSFS_getSearchPath;
    da_PHYSFS_setSaneConfig PHYSFS_setSaneConfig;
    da_PHYSFS_mkdir PHYSFS_mkdir;
    da_PHYSFS_delete PHYSFS_delete;
    da_PHYSFS_getRealDir PHYSFS_getRealDir;
    da_PHYSFS_enumerateFiles PHYSFS_enumerateFiles;
    da_PHYSFS_exists PHYSFS_exists;
    da_PHYSFS_isDirectory PHYSFS_isDirectory;
    da_PHYSFS_isSymbolicLink PHYSFS_isSymbolicLink;
    da_PHYSFS_getLastModTime PHYSFS_getLastModTime;
    da_PHYSFS_openWrite PHYSFS_openWrite;
    da_PHYSFS_openAppend PHYSFS_openAppend;
    da_PHYSFS_openRead PHYSFS_openRead;
    da_PHYSFS_close PHYSFS_close;
    da_PHYSFS_read PHYSFS_read;
    da_PHYSFS_write PHYSFS_write;
    da_PHYSFS_eof PHYSFS_eof;
    da_PHYSFS_tell PHYSFS_tell;
    da_PHYSFS_seek PHYSFS_seek;
    da_PHYSFS_fileLength PHYSFS_fileLength;
    da_PHYSFS_setBuffer PHYSFS_setBuffer;
    da_PHYSFS_flush PHYSFS_flush;
    da_PHYSFS_swapSLE16 PHYSFS_swapSLE16;
    da_PHYSFS_swapULE16 PHYSFS_swapULE16;
    da_PHYSFS_swapSLE32 PHYSFS_swapSLE32;
    da_PHYSFS_swapULE32 PHYSFS_swapULE32;
    da_PHYSFS_swapSLE64 PHYSFS_swapSLE64;
    da_PHYSFS_swapULE64 PHYSFS_swapULE64;
    da_PHYSFS_swapSBE16 PHYSFS_swapSBE16;
    da_PHYSFS_swapUBE16 PHYSFS_swapUBE16;
    da_PHYSFS_swapSBE32 PHYSFS_swapSBE32;
    da_PHYSFS_swapUBE32 PHYSFS_swapUBE32;
    da_PHYSFS_swapSBE64 PHYSFS_swapSBE64;
    da_PHYSFS_swapUBE64 PHYSFS_swapUBE64;
    da_PHYSFS_readSLE16 PHYSFS_readSLE16;
    da_PHYSFS_readULE16 PHYSFS_readULE16;
    da_PHYSFS_readSLE32 PHYSFS_readSLE32;
    da_PHYSFS_readULE32 PHYSFS_readULE32;
    da_PHYSFS_readSLE64 PHYSFS_readSLE64;
    da_PHYSFS_readULE64 PHYSFS_readULE64;
    da_PHYSFS_readSBE16 PHYSFS_readSBE16;
    da_PHYSFS_readUBE16 PHYSFS_readUBE16;
    da_PHYSFS_readSBE32 PHYSFS_readSBE32;
    da_PHYSFS_readUBE32 PHYSFS_readUBE32;
    da_PHYSFS_readSBE64 PHYSFS_readSBE64;
    da_PHYSFS_readUBE64 PHYSFS_readUBE64;
    da_PHYSFS_writeSLE16 PHYSFS_writeSLE16;
    da_PHYSFS_writeULE16 PHYSFS_writeULE16;
    da_PHYSFS_writeSLE32 PHYSFS_writeSLE32;
    da_PHYSFS_writeULE32 PHYSFS_writeULE32;
    da_PHYSFS_writeSLE64 PHYSFS_writeSLE64;
    da_PHYSFS_writeULE64 PHYSFS_writeULE64;
    da_PHYSFS_writeSBE16 PHYSFS_writeSBE16;
    da_PHYSFS_writeUBE16 PHYSFS_writeUBE16;
    da_PHYSFS_writeSBE32 PHYSFS_writeSBE32;
    da_PHYSFS_writeUBE32 PHYSFS_writeUBE32;
    da_PHYSFS_writeSBE64 PHYSFS_writeSBE64;
    da_PHYSFS_writeUBE64 PHYSFS_writeUBE64;
    da_PHYSFS_isInit PHYSFS_isInit;
    da_PHYSFS_symbolicLinksPermitted PHYSFS_symbolicLinksPermitted;
    da_PHYSFS_setAllocator PHYSFS_setAllocator;
    da_PHYSFS_mount PHYSFS_mount;
    da_PHYSFS_getMountPoint PHYSFS_getMountPoint;
    da_PHYSFS_getCdRomDirsCallback PHYSFS_getCdRomDirsCallback;
    da_PHYSFS_getSearchPathCallback PHYSFS_getSearchPathCallback;
    da_PHYSFS_enumerateFilesCallback PHYSFS_enumerateFilesCallback;
    da_PHYSFS_utf8FromUcs4 PHYSFS_utf8FromUcs4;
    da_PHYSFS_utf8ToUcs4 PHYSFS_utf8ToUcs4;
    da_PHYSFS_utf8FromUcs2 PHYSFS_utf8FromUcs2;
    da_PHYSFS_utf8ToUcs2 PHYSFS_utf8ToUcs2;
    da_PHYSFS_utf8FromLatin1 PHYSFS_utf8FromLatin1;

    da_PHYSFS_caseFold PHYSFS_caseFold;
    da_PHYSFS_utf8stricmp PHYSFS_utf8stricmp;
    da_PHYSFS_utf16stricmp PHYSFS_utf16stricmp;
    da_PHYSFS_ucs4stricmp PHYSFS_ucs4stricmp;
    da_PHYSFS_enumerate PHYSFS_enumerate;
    da_PHYSFS_unmount PHYSFS_unmount;
    da_PHYSFS_getAllocator PHYSFS_getAllocator;
    da_PHYSFS_stat PHYSFS_stat;
    da_PHYSFS_utf8FromUtf16 PHYSFS_utf8FromUtf16;
    da_PHYSFS_utf8ToUtf16 PHYSFS_utf8ToUtf16;
    da_PHYSFS_readBytes PHYSFS_readBytes;
    da_PHYSFS_writeBytes PHYSFS_writeBytes;
    da_PHYSFS_mountIo PHYSFS_mountIo;
    da_PHYSFS_mountMemory PHYSFS_mountMemory;
    da_PHYSFS_mountHandle PHYSFS_mountHandle;
    da_PHYSFS_getLastErrorCode PHYSFS_getLastErrorCode;
    da_PHYSFS_getErrorByCode PHYSFS_getErrorByCode;
    da_PHYSFS_setErrorCode PHYSFS_setErrorCode;
    da_PHYSFS_getPrefDir PHYSFS_getPrefDir;
    da_PHYSFS_registerArchiver PHYSFS_registerArchiver;
    da_PHYSFS_deregisterArchiver PHYSFS_deregisterArchiver;
    da_PHYSFS_setRoot PHYSFS_setRoot;
}
